# Generated by Django 3.2.5 on 2022-01-18 06:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名字')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='小名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
            ],
            options={
                'verbose_name': '婴儿信息',
                'verbose_name_plural': '婴儿信息',
                'db_table': 'baby',
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_sleep', to='baby.baby', verbose_name='关联婴儿')),
            ],
            options={
                'verbose_name': '睡眠管理',
                'verbose_name_plural': '睡眠管理',
                'db_table': 'sleep',
            },
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('eat_type', models.IntegerField(choices=[(0, '母乳亲喂'), (1, '母乳瓶喂'), (2, '配方奶')], default=0, verbose_name='喂养方式')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_eat', to='baby.baby', verbose_name='关联婴儿')),
            ],
            options={
                'verbose_name': ('进食管理',),
                'verbose_name_plural': ('进食管理',),
                'db_table': 'eat',
            },
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('has_feces', models.BooleanField(default=False, verbose_name='是否有便便')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_diaper', to='baby.baby', verbose_name='关联婴儿')),
            ],
            options={
                'verbose_name': ('换尿布管理',),
                'verbose_name_plural': ('换尿布管理',),
                'db_table': 'diaper',
            },
        ),
    ]
