# Generated by Django 3.2.5 on 2022-01-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eat',
            name='baby',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='baby',
        ),
        migrations.DeleteModel(
            name='Diaper',
        ),
        migrations.DeleteModel(
            name='Eat',
        ),
        migrations.DeleteModel(
            name='Sleep',
        ),
    ]
