# Generated by Django 3.2.5 on 2022-01-18 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_auto_20220118_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('height', models.FloatField(verbose_name='身高')),
                ('weight', models.FloatField(verbose_name='体重')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_growth', to='baby.baby', verbose_name='关联婴儿')),
            ],
            options={
                'verbose_name': '生长记录',
                'verbose_name_plural': '生长记录',
                'db_table': 'growth',
            },
        ),
    ]
