# Generated by Django 3.2.5 on 2022-01-18 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_growth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='LifeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.IntegerField(default=None, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=None, null=True, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='记录正文')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_life', to='baby.baby', verbose_name='关联婴儿')),
                ('images', models.ManyToManyField(related_name='images', to='baby.Images', verbose_name='照片')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Growth',
        ),
    ]
