# Generated by Django 3.2.5 on 2022-01-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0005_auto_20220118_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '相册管理', 'verbose_name_plural': '相册管理'},
        ),
        migrations.AlterModelTable(
            name='images',
            table='images',
        ),
    ]
