# Generated by Django 3.2.5 on 2022-01-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaper',
            options={'verbose_name': '尿布管理', 'verbose_name_plural': '尿布管理'},
        ),
    ]
